#!/usr/bin/env node
// Writes content.inline.js from content.json so the page works offline, even from file://.
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..');
const data = JSON.parse(fs.readFileSync(path.join(root, 'content.json'), 'utf8'));
fs.writeFileSync(path.join(root, 'content.inline.js'), '/* Generated by tools/inline-content.js from content.json. Do not edit. */\nwindow.CONTENT = ' + JSON.stringify(data) + ';\n');
console.log('content.inline.js written');
